/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beans;

/**
 *
 * @author HarshitMaurya
 */
public class NumericToString extends javax.swing.JFrame {

    /**
     * Creates new form NumericToString
     */
    public NumericToString() {
        initComponents();
    }
String help0to9()
{
    char arr[]=input.getText().toCharArray();
for(int i=0; i<arr.length; i++)
{
    System.out.println(arr.length+"Lenth");
    if(arr[i]=='1')
    {
        System.out.println(arr[i]+" One");
        output.setText("One");
        return output.getText();
    }
    else if(arr[i]=='2')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Two");
    } 
     else if(arr[i]=='3')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Three");
    } 
     else if(arr[i]=='4')
    {
           System.out.println(arr[i]+"Four");
      
        output.setText("Four");
    } 
     else if(arr[i]=='5')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Five");
    } 
      else if(arr[i]=='6')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Six");
    } 
     else if(arr[i]=='7')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Seven");
    } 
     else if(arr[i]=='8')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Eight");
    } 
     else if(arr[i]=='9')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Nine");
    } 
      else if(arr[i]=='0')
    {
      
        output.setText("Zero");
    }
}
return output.getText();
}
String Help100()
{
    char arr[]=input.getText().toCharArray();
String ar="";
for(int j=0; j<arr.length; j++)
{
ar=ar+arr[j];
}     
for(int i=0; i<arr.length; i++)
{
    if("10".equals(ar) || arr[i]=='1')
    {
      
        output.setText("Ten");
              return output.getText();
    } 
  else  if("20".equals(ar) || arr[i]=='2')
    {
        output.setText("Twenty");
              return output.getText();
    } 
        else if(ar.equals("30") || arr[i]=='3')
        {
          output.setText("Thirty");
          return output.getText();
        }
         else if(ar.equals("40") || arr[i]=='4')
        {
          output.setText("Forty");
              return output.getText();
        }
          else if(ar.equals("50") || arr[0]=='5' && arr[1]=='0')
        {
          output.setText("Fifty");
                return output.getText();
        }
           else if(ar.equals("60") || arr[i]=='6')
        {
          output.setText("Sixty");
                return output.getText();
        }
            else if(ar.equals("70") || arr[i]=='7')
        {
          output.setText("Seventy");
                return output.getText();
        }
             else if(ar.equals("80") || arr[i]=='8')
        {
          output.setText("Eighty");
                return output.getText();
        }
              else if(ar.equals("90") || arr[i]=='9')
        {
          output.setText("Ninty");
                return output.getText();
        }
                else if(ar.equals("100"))
        {
          output.setText("Hundred");
                return output.getText();
        } 
}
return output.getText();
}
void Help10To100()
{
    char arr[]=input.getText().toCharArray();
String ar="";
for(int j=0; j<arr.length; j++)
{
ar=ar+arr[j];
}     
for(int i=0; i<arr.length; i++)
{
 if("11".equals(ar))
    {
        output.setText("Eleven");
    } 
       else   if("12".equals(ar))
    {
        output.setText("Toile");
    } 
         else   if("13".equals(ar))
    {
        output.setText("Thirteen");
    } 
         else   if("14".equals(ar))
    {
        output.setText("Fourteen");
    } 
         else   if("15".equals(ar))
    {
        output.setText("Fifteen");
    } 
         else   if("16".equals(ar))
    {
        output.setText("Sixteen");
    } 
         else   if("17".equals(ar))
    {
        output.setText("Seventenn");
    } 
         else   if("18".equals(ar))
    {
        output.setText("Eighteen");
    } 
        else   if("19".equals(ar))
    {
        output.setText("Nineteen");
    } 
   
              
        else 
    {
        System.out.println(Help100()+" Testing  "+help0to9());
                   output.setText(Help100()+" " +help0to9());
    } 
   
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        input = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        output = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        input.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton1.setText("Click");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        output.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        output.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
char arr[]=input.getText().toCharArray();
String ar="";
for(int j=0; j<arr.length; j++)
{
ar=ar+arr[j];
}     
for(int i=0; i<arr.length; i++)
{
    System.out.println(arr.length+"Lenth");
    if(arr.length==1)
    {
        
    if(arr[i]=='1')
    {
        System.out.println(arr[i]+" One");
        output.setText("One");
    }
    else if(arr[i]=='2')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Two");
    } 
     else if(arr[i]=='3')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Three");
    } 
     else if(arr[i]=='4')
    {
           System.out.println(arr[i]+"Four");
      
        output.setText("Four");
    } 
     else if(arr[i]=='5')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Five");
    } 
      else if(arr[i]=='6')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Six");
    } 
     else if(arr[i]=='7')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Seven");
    } 
     else if(arr[i]=='8')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Eight");
    } 
     else if(arr[i]=='9')
    {
           System.out.println(arr[i]+"Two");
      
        output.setText("Nine");
    } 
      else if(arr[i]=='0')
    {
      
        output.setText("Zero");
    } 
    }
      if(arr.length>1)
      {
    System.out.println(ar);
     Help10To100();
          Help100();
      }
      
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumericToString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumericToString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumericToString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumericToString.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumericToString().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel output;
    // End of variables declaration//GEN-END:variables
}
