/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedicalStore;

import javax.swing.JOptionPane;

/**
 *
 * @author HarshitMaurya
 */
public class signupn extends javax.swing.JFrame {

    /**
     * Creates new form signupn
     */
    public signupn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel64 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        signupnewpass = new javax.swing.JTextField();
        signuppass = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        signupuser = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel64.setText("Re Enter password");
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 120, -1));

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton19.setText("SignUp Here !");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        signupnewpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signupnewpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signupnewpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(signupnewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 260, 30));

        signuppass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signuppass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signuppass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(signuppass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 260, 30));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel63.setText("Password");
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 70, -1));

        signupuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signupuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signupuser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(signupuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 260, 30));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel65.setText("Username");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 70, -1));

        jLabel66.setFont(new java.awt.Font("Trajan Pro 3", 1, 36)); // NOI18N
        jLabel66.setText("Sign UP ");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 230, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -5, 1290, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try
        {
            String newuser=signupuser.getText();
            String newuserpass=signuppass.getText();
            String newuserrepass=signupnewpass.getText();
            DBConnection db=new DBConnection();

            if(newuserpass.equalsIgnoreCase(newuserrepass))
            {
                db.pstmt=db.con.prepareStatement("insert into login_details(username,password) values(?,?)");
                db.pstmt.setString(1, newuser);
                db.pstmt.setString(2,newuserpass);
                int i= db.pstmt.executeUpdate();
                if(i>0)
                {
                    JOptionPane.showMessageDialog(this,"Your Account Is Created Succesfully");
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"An Error Accourd !");                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Password nOT Matched !");
            }

        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField signupnewpass;
    private javax.swing.JTextField signuppass;
    private javax.swing.JTextField signupuser;
    // End of variables declaration//GEN-END:variables
}
