/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plantstore;

import com.sun.xml.internal.bind.v2.schemagen.Util;
import java.util.Scanner;

/**
 *
 * @author HarshitMaurya
 */
public class splash extends javax.swing.JFrame {

  void prosplash()
  {
     
          }
          public splash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();
        pbar = new javax.swing.JProgressBar();
        pload = new javax.swing.JLabel();
        tipes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 1, 52)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("plant Softwere");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, 60));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome, To Our Plant Softwere");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        loading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        loading.setForeground(new java.awt.Color(255, 255, 255));
        loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loading.setText("99%");
        jPanel1.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        pbar.setBackground(new java.awt.Color(255, 255, 255));
        pbar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pbar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(pbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 970, 40));

        pload.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pload.setForeground(new java.awt.Color(255, 255, 255));
        pload.setText("Loading...");
        jPanel1.add(pload, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 160, 50));

        tipes.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tipes.setForeground(new java.awt.Color(255, 255, 255));
        tipes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tipes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 440, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image from million-wallpapers.com 1233d5x600.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1235, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {                                //UserName :- root
                                                                                                              //Password :- 1234
       splash s=new splash();
     s.setVisible(true);
    
        try
      {
        for(int i=0; i<=100; i++)
        {
           
            Thread.sleep(58);
            loading.setText(Integer.toString(i)+"%");
            pbar.setValue(i);
            if(i%2==0)
            {
               
                pload.setText("Loading....");
            }
            else
            {
                pload.setText("Loading..");
            }
            if(i>10 && i<35)
            {
                
                tipes.setText("Any Time You Can Change You Password !");
            }
            else
            {
                tipes.setText("");
            }
             if(i>50 && i<75)
            {
                
                tipes.setText("Have any Problem ?, Fedback@rockharshitmaurya");
            }
            else
            {
                tipes.setText("");
            }
            if(i==100)
            {
                
                PlantStore lg=new PlantStore();
                lg.setVisible(true);
                s.setVisible(false);
            }
        }
      }
      catch(Exception e)
      {
          e.printStackTrace();
      }
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private static javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JLabel loading;
    private static javax.swing.JProgressBar pbar;
    private static javax.swing.JLabel pload;
    private static javax.swing.JLabel tipes;
    // End of variables declaration//GEN-END:variables
}
