/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SocietyManagmentSystem;

import java.awt.Color;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author HarshitMaurya
 */
public class AdminAddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form CouriourManagementSystem
     */
    public AdminAddEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        EngineerAddress = new javax.swing.JTextField();
        EngineerContact = new javax.swing.JTextField();
        EngineerDesig = new javax.swing.JTextField();
        EngineerEmail = new javax.swing.JTextField();
        EngineerName1 = new javax.swing.JTextField();
        EngineerName = new javax.swing.JTextField();
        EngineerMonth = new javax.swing.JComboBox<>();
        EngineerYear = new javax.swing.JComboBox<>();
        EngineerDay = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel68 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel67 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Trajan Pro 3", 1, 48)); // NOI18N
        jLabel7.setText("Adding New Employee");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<<");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ID");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 160, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Contact No :");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Date Of Birth :");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("New Password :");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, -1, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Address :");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Designation :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        EngineerAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EngineerAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EngineerAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EngineerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineerAddressActionPerformed(evt);
            }
        });
        jPanel5.add(EngineerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 300, 30));

        EngineerContact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EngineerContact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EngineerContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EngineerContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineerContactActionPerformed(evt);
            }
        });
        jPanel5.add(EngineerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 300, 30));

        EngineerDesig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EngineerDesig.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EngineerDesig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EngineerDesig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineerDesigActionPerformed(evt);
            }
        });
        jPanel5.add(EngineerDesig, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 300, 30));

        EngineerEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EngineerEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EngineerEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EngineerEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineerEmailActionPerformed(evt);
            }
        });
        jPanel5.add(EngineerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 300, 30));

        EngineerName1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EngineerName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EngineerName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EngineerName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineerName1ActionPerformed(evt);
            }
        });
        jPanel5.add(EngineerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 300, 30));

        EngineerName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EngineerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EngineerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EngineerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineerNameActionPerformed(evt);
            }
        });
        jPanel5.add(EngineerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 300, 30));

        EngineerMonth.setBackground(new java.awt.Color(153, 153, 153));
        EngineerMonth.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EngineerMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        EngineerMonth.setBorder(null);
        jPanel5.add(EngineerMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 70, 30));

        EngineerYear.setBackground(new java.awt.Color(153, 153, 153));
        EngineerYear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EngineerYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", " ", " " }));
        EngineerYear.setBorder(null);
        jPanel5.add(EngineerYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 70, 30));

        EngineerDay.setBackground(new java.awt.Color(153, 153, 153));
        EngineerDay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EngineerDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        EngineerDay.setBorder(null);
        jPanel5.add(EngineerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 70, 30));

        jPasswordField1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 300, 30));

        jLabel68.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Username :");
        jPanel5.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        jButton2.setText("Clear");
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, 120, 40));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        jButton3.setText("Add");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 100, 40));

        jLabel67.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Employee's Name :");
        jPanel5.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        jLabel96.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel96.setText("Employee's ID :");
        jPanel5.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("E-Mail :");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 100, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image from million-wallpapers.com 1366x768 (6).jpg"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1320, 700));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1320, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
this.setVisible(false);//        AdminAddEmployee.setVisible(false);
    //    AdminControlPanel.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void EngineerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngineerAddressActionPerformed

    private void EngineerContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineerContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngineerContactActionPerformed

    private void EngineerDesigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineerDesigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngineerDesigActionPerformed

    private void EngineerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngineerEmailActionPerformed

    private void EngineerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngineerNameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DBConnection db=new DBConnection();

        String day=EngineerDay.getSelectedItem().toString();
        String month=EngineerMonth.getSelectedItem().toString();
        String year=EngineerYear.getSelectedItem().toString();
        try
        {
            db.pstmt=db.con.prepareStatement("select MAX(s_no) from employee");
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next())
            {
                String Eid="Emp0043";
                jLabel9.setText(Eid+db.rst.getString(1));
            }
            String EmployeIDstore=jLabel9.getText();
            db.pstmt=db.con.prepareStatement("insert into employee(e_name,adress,dob,contact_no,desig,email,e_id,username) values(?,?,?,?,?,?,?,?)");
            db.pstmt.setString(1,EngineerName.getText());
            db.pstmt.setString(2, EngineerAddress.getText());
            db.pstmt.setString(3,year+"-"+month+"-"+day);
            db.pstmt.setString(4,EngineerContact.getText());
            db.pstmt.setString(5, EngineerDesig.getText());
            db.pstmt.setString(6, EngineerEmail.getText());
            db.pstmt.setString(7,EmployeIDstore);
            db.pstmt.setString(8, EngineerName1.getText());
            int i= db.pstmt.executeUpdate();
            if(i>0)
            {
 db.pstmt=db.con.prepareStatement("insert into login_user(username,password,Type) values(?,?,?)");
 db.pstmt.setString(1,EngineerName1.getText());
 db.pstmt.setString(2,jPasswordField1.getText());
 db.pstmt.setString(3,"Employee");
 int j=db.pstmt.executeUpdate();
 if(i>0)
 {
     
                JOptionPane.showMessageDialog(this,"Employee Added !");
 }
 else
 {
     JOptionPane.showMessageDialog(this,"Somthing Went Wrong");
 }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Error !");
            }

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void EngineerName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineerName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngineerName1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
jButton3.setBackground(Color.green);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
Color c=new Color(153,153,153);
        jButton3.setBackground(c);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EngineerAddress;
    private javax.swing.JTextField EngineerContact;
    private javax.swing.JComboBox<String> EngineerDay;
    private javax.swing.JTextField EngineerDesig;
    private javax.swing.JTextField EngineerEmail;
    private javax.swing.JComboBox<String> EngineerMonth;
    private javax.swing.JTextField EngineerName;
    private javax.swing.JTextField EngineerName1;
    private javax.swing.JComboBox<String> EngineerYear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
