/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SocietyManagmentSystem;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author HarshitMaurya
 */
public class AdminContrlPanel extends javax.swing.JFrame {

    /**
     * Creates new form CouriourManagementSystem
     */
    public AdminContrlPanel() {
        super("Society Managment System");
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jSeparator58 = new javax.swing.JSeparator();
        jSeparator57 = new javax.swing.JSeparator();
        jSeparator56 = new javax.swing.JSeparator();
        jSeparator59 = new javax.swing.JSeparator();
        jButton19 = new javax.swing.JButton();
        jSeparator52 = new javax.swing.JSeparator();
        jSeparator53 = new javax.swing.JSeparator();
        jSeparator54 = new javax.swing.JSeparator();
        jSeparator55 = new javax.swing.JSeparator();
        jButton18 = new javax.swing.JButton();
        jSeparator60 = new javax.swing.JSeparator();
        jSeparator63 = new javax.swing.JSeparator();
        jSeparator62 = new javax.swing.JSeparator();
        jSeparator61 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jSeparator51 = new javax.swing.JSeparator();
        jButton20 = new javax.swing.JButton();
        jSeparator64 = new javax.swing.JSeparator();
        jSeparator65 = new javax.swing.JSeparator();
        jSeparator66 = new javax.swing.JSeparator();
        jSeparator67 = new javax.swing.JSeparator();
        jSeparator68 = new javax.swing.JSeparator();
        jSeparator69 = new javax.swing.JSeparator();
        jSeparator70 = new javax.swing.JSeparator();
        jSeparator71 = new javax.swing.JSeparator();
        jButton21 = new javax.swing.JButton();
        jSeparator72 = new javax.swing.JSeparator();
        jSeparator73 = new javax.swing.JSeparator();
        jSeparator74 = new javax.swing.JSeparator();
        jSeparator75 = new javax.swing.JSeparator();
        jButton22 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setBackground(new java.awt.Color(0, 51, 51));
        jButton17.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Add Member");
        jButton17.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton17MouseExited(evt);
            }
        });
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 130, 220, 140));
        jPanel1.add(jSeparator58, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 120, 240, 20));

        jSeparator57.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator57, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 120, 10, 160));
        jPanel1.add(jSeparator56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, 240, 20));

        jSeparator59.setForeground(new java.awt.Color(0, 0, 204));
        jSeparator59.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 120, 30, 160));

        jButton19.setBackground(new java.awt.Color(0, 51, 51));
        jButton19.setFont(new java.awt.Font("Sitka Heading", 1, 31)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Add Employee ");
        jButton19.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton19MouseExited(evt);
            }
        });
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 220, 140));

        jSeparator52.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(jSeparator52, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 240, 20));

        jSeparator53.setForeground(new java.awt.Color(0, 0, 204));
        jSeparator53.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator53, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 30, 160));
        jPanel1.add(jSeparator54, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 240, 20));

        jSeparator55.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator55, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 10, 160));

        jButton18.setBackground(new java.awt.Color(0, 51, 51));
        jButton18.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Add Worker");
        jButton18.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton18MouseExited(evt);
            }
        });
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 220, 140));
        jPanel1.add(jSeparator60, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 240, 20));

        jSeparator63.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator63, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 10, 160));
        jPanel1.add(jSeparator62, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, 240, 20));

        jSeparator61.setForeground(new java.awt.Color(0, 0, 204));
        jSeparator61.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator61, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 30, 160));

        jLabel40.setFont(new java.awt.Font("Trajan Pro 3", 1, 65)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("admin control panel");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));
        jPanel1.add(jSeparator51, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 920, 20));

        jButton20.setBackground(new java.awt.Color(0, 51, 51));
        jButton20.setFont(new java.awt.Font("Sitka Heading", 1, 29)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("Manage Details");
        jButton20.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton20MouseExited(evt);
            }
        });
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 530, 220, 140));
        jPanel1.add(jSeparator64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 680, 240, 20));

        jSeparator65.setForeground(new java.awt.Color(0, 0, 204));
        jSeparator65.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator65, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 520, 30, 160));
        jPanel1.add(jSeparator66, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 520, 240, 20));

        jSeparator67.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator67, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 520, 10, 160));
        jPanel1.add(jSeparator68, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 240, 20));

        jSeparator69.setForeground(new java.awt.Color(0, 0, 204));
        jSeparator69.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator69, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 30, 160));

        jSeparator70.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(jSeparator70, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 240, 20));

        jSeparator71.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator71, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 10, 160));

        jButton21.setBackground(new java.awt.Color(0, 51, 51));
        jButton21.setFont(new java.awt.Font("Sitka Heading", 1, 28)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Salary Overview");
        jButton21.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton21MouseExited(evt);
            }
        });
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 220, 140));
        jPanel1.add(jSeparator72, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 320, 240, 20));

        jSeparator73.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator73, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 320, 10, 160));
        jPanel1.add(jSeparator74, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 480, 240, 20));

        jSeparator75.setForeground(new java.awt.Color(0, 0, 204));
        jSeparator75.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator75, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 320, 30, 160));

        jButton22.setBackground(new java.awt.Color(0, 51, 51));
        jButton22.setFont(new java.awt.Font("Sitka Heading", 1, 26)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Gate InOut Details");
        jButton22.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton22MouseExited(evt);
            }
        });
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 330, 220, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image from million-wallpapers.com 1355x723.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1355, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseEntered
         Color c=new Color(11,22,53);
        jButton17.setBackground(c);
               jButton20.setBackground(Color.BLACK); 
        jButton19.setBackground(Color.black);
        jButton18.setBackground(Color.black);
             jButton21.setBackground(Color.BLACK);
            jButton22.setBackground(Color.BLACK);
    }//GEN-LAST:event_jButton17MouseEntered

    private void jButton17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseExited
             Color c=new Color(0,51,51);
        jButton17.setBackground(c);
        jButton19.setBackground(c);
        jButton18.setBackground(c);
        jButton20.setBackground(c);
          jButton21.setBackground(c);
            jButton22.setBackground(c);
    }//GEN-LAST:event_jButton17MouseExited

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
new AdminAddMemebers().setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseEntered
        jButton17.setBackground(Color.black);
 Color c=new Color(11,22,53);
        jButton19.setBackground(c);
        jButton18.setBackground(Color.black);
        jButton20.setBackground(Color.BLACK);
          jButton21.setBackground(Color.BLACK);
            jButton22.setBackground(Color.BLACK);
    }//GEN-LAST:event_jButton19MouseEntered

    private void jButton19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseExited
        Color c=new Color(0,51,51);
        jButton17.setBackground(c);
        jButton19.setBackground(c);
        jButton18.setBackground(c);
        jButton20.setBackground(c);
          jButton21.setBackground(c);
            jButton22.setBackground(c);
    }//GEN-LAST:event_jButton19MouseExited

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
new AdminAddEmployee().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseEntered
        jButton19.setBackground(Color.BLACK);
        jButton17.setBackground(Color.BLACK);
     Color c=new Color(11,22,53);
        jButton18.setBackground(c);
                jButton20.setBackground(Color.BLACK);
                     jButton21.setBackground(Color.BLACK);
            jButton22.setBackground(Color.BLACK);
    }//GEN-LAST:event_jButton18MouseEntered

    private void jButton18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseExited
        Color c=new Color(0,51,51);
        jButton19.setBackground(c);
        jButton17.setBackground(c);
        jButton18.setBackground(c);
        jButton20.setBackground(c);
    }//GEN-LAST:event_jButton18MouseExited

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
new AdminAddWorker().setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseEntered
   jButton19.setBackground(Color.BLACK);
        jButton17.setBackground(Color.BLACK);
     Color c=new Color(11,22,53);
        jButton18.setBackground(Color.BLACK);
                jButton20.setBackground(c);    
                     jButton21.setBackground(Color.BLACK);
            jButton22.setBackground(Color.BLACK);// TODO add your handling code here:
    }//GEN-LAST:event_jButton20MouseEntered

    private void jButton20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseExited
          Color c=new Color(0,51,51);
        jButton17.setBackground(c);
        jButton19.setBackground(c);
        jButton18.setBackground(c);
        jButton20.setBackground(c);
          jButton21.setBackground(c);
            jButton22.setBackground(c);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton20MouseExited

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
new UpdateEmployeeAndMember().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseEntered
        jButton17.setBackground(Color.black);
 Color c=new Color(11,22,53);
 jButton21.setBackground(c);
 jButton22.setBackground(Color.BLACK);
        jButton19.setBackground(Color.black);
        jButton18.setBackground(Color.black);
        jButton20.setBackground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21MouseEntered

    private void jButton21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseExited
       Color c=new Color(0,51,51);
        jButton17.setBackground(c);
        jButton19.setBackground(c);
        jButton18.setBackground(c);
        jButton20.setBackground(c);
          jButton21.setBackground(c);
            jButton22.setBackground(c);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21MouseExited

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
new SalaryDetails().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseEntered
  jButton17.setBackground(Color.black);
 Color c=new Color(11,22,53);
 jButton22.setBackground(c);
 jButton21.setBackground(Color.BLACK);
        jButton19.setBackground(Color.black);
        jButton18.setBackground(Color.black);
        jButton20.setBackground(Color.BLACK);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton22MouseEntered

    private void jButton22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseExited
       Color c=new Color(0,51,51);
        jButton17.setBackground(c);
        jButton19.setBackground(c);
        jButton18.setBackground(c);
        jButton20.setBackground(c);
          jButton21.setBackground(c);
            jButton22.setBackground(c);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22MouseExited

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
new DetailsIncommingOutgoing().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CallMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CallMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CallMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CallMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminContrlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator57;
    private javax.swing.JSeparator jSeparator58;
    private javax.swing.JSeparator jSeparator59;
    private javax.swing.JSeparator jSeparator60;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    private javax.swing.JSeparator jSeparator63;
    private javax.swing.JSeparator jSeparator64;
    private javax.swing.JSeparator jSeparator65;
    private javax.swing.JSeparator jSeparator66;
    private javax.swing.JSeparator jSeparator67;
    private javax.swing.JSeparator jSeparator68;
    private javax.swing.JSeparator jSeparator69;
    private javax.swing.JSeparator jSeparator70;
    private javax.swing.JSeparator jSeparator71;
    private javax.swing.JSeparator jSeparator72;
    private javax.swing.JSeparator jSeparator73;
    private javax.swing.JSeparator jSeparator74;
    private javax.swing.JSeparator jSeparator75;
    // End of variables declaration//GEN-END:variables
}
