/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SocietyManagmentSystem;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HarshitMaurya
 */
public class CallMaintainer extends javax.swing.JFrame {

    /**
     * Creates new form CouriourManagementSystem
     */
    public CallMaintainer() {
        initComponents();
        DBConnection db=new DBConnection();
        try
{
          DefaultListModel dlm2=new DefaultListModel();

  db.pstmt=db.con.prepareStatement("select comp_id from pending_complaint");
  db.rst=db.pstmt.executeQuery();
  while(db.rst.next())
  {
      dlm2.addElement(db.rst.getString(1));
  }
  jList5.setModel(dlm2);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, e);
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        wAddress = new javax.swing.JTextField();
        wcontact = new javax.swing.JTextField();
        wemail = new javax.swing.JTextField();
        wname = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane14 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator38 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jSeparator39 = new javax.swing.JSeparator();
        mname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator42 = new javax.swing.JSeparator();
        jSeparator43 = new javax.swing.JSeparator();
        jSeparator44 = new javax.swing.JSeparator();
        jSeparator45 = new javax.swing.JSeparator();
        jScrollPane15 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        madress = new javax.swing.JTextField();
        mneed = new javax.swing.JTextField();
        mcontact = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Trajan Pro 3", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("search maintainer ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Contact No :");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Complaint I'D");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 70, -1, -1));

        wAddress.setEditable(false);
        wAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wAddressActionPerformed(evt);
            }
        });
        jPanel5.add(wAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 300, 30));

        wcontact.setEditable(false);
        wcontact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wcontact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wcontact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wcontactActionPerformed(evt);
            }
        });
        jPanel5.add(wcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 300, 30));

        wemail.setEditable(false);
        wemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wemailActionPerformed(evt);
            }
        });
        jPanel5.add(wemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 300, 30));

        wname.setEditable(false);
        wname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wnameActionPerformed(evt);
            }
        });
        jPanel5.add(wname, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 300, 30));

        jLabel67.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Worker's Name :");
        jPanel5.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Member Contact :");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, -1, -1));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 590, 20));

        jComboBox1.setBackground(new java.awt.Color(64, 58, 68));
        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maintainer Type", "Electrician", "Plumber", "Watchman" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 30));

        jList4.setBackground(new java.awt.Color(93, 73, 71));
        jList4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jList4.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList4ValueChanged(evt);
            }
        });
        jScrollPane14.setViewportView(jList4);

        jPanel5.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, 230));

        jSeparator40.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 60, 250));
        jPanel5.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 10));

        jSeparator41.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 40, 250));
        jPanel5.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 150, 30));

        mname.setEditable(false);
        mname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });
        jPanel5.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 300, 30));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("Apoint");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, -1, -1));

        jSeparator42.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 100, 60, 250));
        jPanel5.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 350, 150, 30));

        jSeparator44.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 100, 40, 250));
        jPanel5.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 100, 150, 10));

        jList5.setBackground(new java.awt.Color(105, 115, 90));
        jList5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jList5.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList5ValueChanged(evt);
            }
        });
        jScrollPane15.setViewportView(jList5);

        jPanel5.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 110, 130, 230));

        madress.setEditable(false);
        madress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        madress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        madress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        madress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madressActionPerformed(evt);
            }
        });
        jPanel5.add(madress, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 300, 30));

        mneed.setEditable(false);
        mneed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mneed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mneed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mneed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mneedActionPerformed(evt);
            }
        });
        jPanel5.add(mneed, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 300, 30));

        mcontact.setEditable(false);
        mcontact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mcontact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mcontact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcontactActionPerformed(evt);
            }
        });
        jPanel5.add(mcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 300, 30));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Address :");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Member Need :");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, -1, -1));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Member Name :");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("E-Mail :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Member Adress :");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, -1));

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 100, 40));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 650, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image from million-wallpapers.com 1366x768 (3).jpg"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wAddressActionPerformed

    private void wcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wcontactActionPerformed

    private void wemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wemailActionPerformed

    private void wnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wnameActionPerformed

    private void jList4ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList4ValueChanged
        DBConnection db=new DBConnection();
        try
        {
            db.pstmt=db.con.prepareStatement("select * from worker where w_id=?");
            db.pstmt.setString(1,jList4.getSelectedValue());
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next())
            {
             wname.setText(db.rst.getString(1));
             wAddress.setText(db.rst.getString(3));
             wcontact.setText("+91"+db.rst.getString(2));
             wemail.setText(db.rst.getString(8));
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jList4ValueChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
DBConnection db=new DBConnection();
        try
{
          DefaultListModel dlm=new DefaultListModel();

  db.pstmt=db.con.prepareStatement("select w_id from worker where w_type=?");
  db.pstmt.setString(1, jComboBox1.getSelectedItem()+"");
  db.rst=db.pstmt.executeQuery();
  while(db.rst.next())
  {
      dlm.addElement(db.rst.getString(1));
  }
  jList4.setModel(dlm);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, e);
}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DBConnection db=new DBConnection();
        try
{
    db.pstmt=db.con.prepareStatement("insert into actioned_complaints(w_name,w_address,w_no,w_mail,m_name,m_contact,m_address,m_need,w_id,comp_id,curdate) values(?,?,?,?,?,?,?,?,?,?,curdate())");
    db.pstmt.setString(1, wname.getText());
    db.pstmt.setString(2, wAddress.getText());
    db.pstmt.setString(3, wcontact.getText());
    db.pstmt.setString(4, wemail.getText());
    db.pstmt.setString(5, mname.getText());
    db.pstmt.setString(6, mcontact.getText());
    db.pstmt.setString(7, madress.getText());
    db.pstmt.setString(8, mneed.getText());
    db.pstmt.setString(9, jList4.getSelectedValue());
    db.pstmt.setString(10, jList5.getSelectedValue());
    int i=db.pstmt.executeUpdate();
    if(i>0)
    {
        JOptionPane.showMessageDialog(this,"Complaint Handled");
        jComboBox1.setSelectedIndex(0);
        db.pstmt=db.con.prepareStatement("delete from pending_complaint where comp_id=?");
        db.pstmt.setString(1,jList5.getSelectedValue());
        int h=db.pstmt.executeUpdate();
        if(h>0)
        {
            
        }
    }
    else
    {
        JOptionPane.showMessageDialog(this,"Somthing Went Wrong !");
    }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameActionPerformed

    private void jList5ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList5ValueChanged
        DBConnection db=new DBConnection();
        try
        {
            db.pstmt=db.con.prepareStatement("select * from pending_complaint where comp_id=?");
            db.pstmt.setString(1,jList5.getSelectedValue());
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next())
            {
             mname.setText(db.rst.getString(1));
             madress.setText(db.rst.getString(4));
             mcontact.setText("+91"+db.rst.getString(2));
             mneed.setText(db.rst.getString(5));
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jList5ValueChanged

    private void madressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_madressActionPerformed

    private void mcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcontactActionPerformed

    private void mneedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mneedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mneedActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 wname.setText("");
  wAddress.setText("");
   wcontact.setText("");
    wemail.setText("");
    mname.setText("");
   mcontact.setText("");
   madress.setText("");
    mneed.setText("");
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
  jButton1.setBackground(Color.green);
  jButton3.setBackground(Color.red);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
      Color c=new Color(153,153,153);
        jButton3.setBackground(c);   
        jButton1.setBackground(c);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
   Color c=new Color(153,153,153);
        jButton3.setBackground(c);   
        jButton1.setBackground(c);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
 jButton1.setBackground(Color.red);
  jButton3.setBackground(Color.green);
    }//GEN-LAST:event_jButton3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CallMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CallMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CallMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CallMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CallMaintainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JTextField madress;
    private javax.swing.JTextField mcontact;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField mneed;
    private javax.swing.JTextField wAddress;
    private javax.swing.JTextField wcontact;
    private javax.swing.JTextField wemail;
    private javax.swing.JTextField wname;
    // End of variables declaration//GEN-END:variables
}
