/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SocietyManagmentSystem;

import java.awt.Color;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HarshitMaurya
 */
public class EmployeePayMaintainer extends javax.swing.JFrame {

    /**
     * Creates new form CouriourManagementSystem
     */
    public EmployeePayMaintainer() {
        initComponents();
      /*  DBConnection db=new DBConnection();
       try
       {
           Calendar c=Calendar.getInstance();
                    int currentdate=c.get(Calendar.DATE);
                    int currentmonth=c.get(Calendar.MONTH);
                    int currentyear=c.get(Calendar.YEAR);
                    int dd,mm,yyyy;
                    int diff;
                    int salary;
                    int totle;
         db.pstmt=db.con.prepareStatement("select last_pay_date,autoupdate,emp_basic_salary from pending_salary");
         db.rst=db.pstmt.executeQuery();
         while(db.rst.next())
         {
                            String date=db.rst.getString(1);
                       
                            dd=Integer.parseInt(date.substring(8));
                            
                            mm=Integer.parseInt(date.substring(5,7));
                           
                        
                            diff=mm-(currentmonth+1);
                            System.out.println(diff);
                            salary=Integer.parseInt(db.rst.getString(3));
                            totle=diff*salary;
                            if(mm!=currentmonth+1)
                            {
                                if(db.rst.getString(2).equalsIgnoreCase("NotUpdated"))
                                {
                               db.pstmt=db.con.prepareStatement("update pending_salary set emp_basic_salary=?,autoupdate=?");
                               db.pstmt.setString(1,totle+"");
                               db.pstmt.setString(2,"Updated");
                               yyyy=db.pstmt.executeUpdate();
                                }
                            } 
                            
         }
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,e);
       }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        wAddress = new javax.swing.JTextField();
        wcontact = new javax.swing.JTextField();
        wid = new javax.swing.JTextField();
        wname = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane14 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator38 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jSeparator39 = new javax.swing.JSeparator();
        salaryfrom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        basicsalary = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        salarypay = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Trajan Pro 3", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("pay Maintainers");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Contact No :");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        wAddress.setEditable(false);
        wAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wAddressActionPerformed(evt);
            }
        });
        jPanel5.add(wAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 300, 30));

        wcontact.setEditable(false);
        wcontact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wcontact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wcontact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wcontactActionPerformed(evt);
            }
        });
        jPanel5.add(wcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 300, 30));

        wid.setEditable(false);
        wid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widActionPerformed(evt);
            }
        });
        jPanel5.add(wid, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 300, 30));

        wname.setEditable(false);
        wname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wnameActionPerformed(evt);
            }
        });
        wname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wnameKeyTyped(evt);
            }
        });
        jPanel5.add(wname, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 300, 30));

        jLabel67.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Search Name :");
        jPanel5.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Salary  Pay :");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, -1, -1));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 560, 20));

        jList4.setBackground(new java.awt.Color(93, 73, 71));
        jList4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jList4.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList4ValueChanged(evt);
            }
        });
        jScrollPane14.setViewportView(jList4);

        jPanel5.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 130, 230));

        jSeparator40.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 60, 250));
        jPanel5.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 150, 10));

        jSeparator41.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 40, 250));
        jPanel5.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 150, 30));

        salaryfrom.setEditable(false);
        salaryfrom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salaryfrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        salaryfrom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        salaryfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryfromActionPerformed(evt);
            }
        });
        jPanel5.add(salaryfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 300, 30));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, -1, -1));

        basicsalary.setEditable(false);
        basicsalary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        basicsalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        basicsalary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        basicsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicsalaryActionPerformed(evt);
            }
        });
        jPanel5.add(basicsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 300, 30));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Home Add :");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Salary From :");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Employee I'd :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 100, 40));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 620, -1, -1));

        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 140, 30));

        jLabel68.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Employee's Name :");
        jPanel5.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        salarypay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salarypay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        salarypay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        salarypay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarypayActionPerformed(evt);
            }
        });
        jPanel5.add(salarypay, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 300, 30));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Basic Salary :");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, -1, -1));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 290, 20));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 660, 290, 20));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 600, 80, 60));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 80, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image from million-wallpapers.com 1366x768 (7).jpg"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wAddressActionPerformed

    private void wcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wcontactActionPerformed

    private void widActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_widActionPerformed

    private void wnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wnameActionPerformed

    private static java.sql.Date getCurrentDate() {
    java.util.Date today = new java.util.Date();
    return new java.sql.Date(today.getTime());
}
    private void jList4ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList4ValueChanged
        DBConnection db=new DBConnection();
        try
        {
            db.pstmt=db.con.prepareStatement("select * from pending_salary where emp_contact=?");
            db.pstmt.setString(1,jList4.getSelectedValue());
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next())
            {
             wname.setText(db.rst.getString(1));
             wAddress.setText(db.rst.getString(2));
             wcontact.setText("+91"+db.rst.getString(3));
             wid.setText(db.rst.getString(6));
             salaryfrom.setText(db.rst.getString(5));
             basicsalary.setText(db.rst.getString(4));
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jList4ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DBConnection db=new DBConnection();
        try
{
    System.out.println(jList4.getSelectedValue());
   db.pstmt=db.con.prepareStatement("update pending_salary set emp_basic_salary=emp_basic_salary-?, last_pay_date=curdate() where emp_contact=?");
   db.pstmt.setString(1, salarypay.getText());
   db.pstmt.setString(2, jList4.getSelectedValue());
   int i=db.pstmt.executeUpdate();
   if(i>0)
   {
       db.pstmt=db.con.prepareStatement("insert into payed_salary(emp_name,emp_contact,emp_add,emp_id,salary_from,totle_salary,salary_payed,curdate) values(?,?,?,?,?,?,?,curdate())");
       db.pstmt.setString(1, wname.getText());
       db.pstmt.setString(2, wcontact.getText());
       db.pstmt.setString(3, wAddress.getText());
       db.pstmt.setString(4, wid.getText());
       db.pstmt.setString(5, salaryfrom.getText());
       db.pstmt.setString(6, basicsalary.getText());
       db.pstmt.setString(7, salarypay.getText());
       int k=db.pstmt.executeUpdate();
       if(k>0)
       {
       JOptionPane.showMessageDialog(this,"Payed Sucessfully");
   }}
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void basicsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basicsalaryActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 wname.setText("");
  wAddress.setText("");
   wcontact.setText("");
    wid.setText("");
    salaryfrom.setText("");
   basicsalary.setText("");
  salarypay.setText("");
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
  jButton1.setBackground(Color.green);
  jButton3.setBackground(Color.red);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
      Color c=new Color(153,153,153);
        jButton3.setBackground(c);   
        jButton1.setBackground(c);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
   Color c=new Color(153,153,153);
        jButton3.setBackground(c);   
        jButton1.setBackground(c);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
 jButton1.setBackground(Color.red);
  jButton3.setBackground(Color.green);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MouseEntered

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
DBConnection db=new DBConnection();
try
{
    DefaultListModel dlm=new DefaultListModel();
    db.pstmt=db.con.prepareStatement("select emp_contact from pending_salary where emp_name like ?");
    db.pstmt.setString(1,"%"+jTextField1.getText()+"%");
    db.rst=db.pstmt.executeQuery();
    while(db.rst.next())
    {
        dlm.addElement(db.rst.getString(1));
    }
    jList4.setModel(dlm);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_jTextField1KeyReleased

    private void salaryfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryfromActionPerformed

    private void wnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wnameKeyTyped

    }//GEN-LAST:event_wnameKeyTyped

    private void salarypayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarypayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarypayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeePayMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeePayMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeePayMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeePayMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeePayMaintainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField basicsalary;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField salaryfrom;
    private javax.swing.JTextField salarypay;
    private javax.swing.JTextField wAddress;
    private javax.swing.JTextField wcontact;
    private javax.swing.JTextField wid;
    private javax.swing.JTextField wname;
    // End of variables declaration//GEN-END:variables
}
