/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SocietyManagmentSystem;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HarshitMaurya
 */
public class IncommindOutGoingDetails extends javax.swing.JFrame {

    /**
     * Creates new form CouriourManagementSystem
     */
    public IncommindOutGoingDetails() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        wAddress = new javax.swing.JTextField();
        wcontact = new javax.swing.JTextField();
        wemail = new javax.swing.JTextField();
        wname = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane14 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jSeparator40 = new javax.swing.JSeparator();
        jSeparator38 = new javax.swing.JSeparator();
        jSeparator41 = new javax.swing.JSeparator();
        jSeparator39 = new javax.swing.JSeparator();
        bnumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fnumber = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Trajan Pro 3", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Details about day");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Contact No :");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        wAddress.setEditable(false);
        wAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wAddressActionPerformed(evt);
            }
        });
        jPanel5.add(wAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 300, 30));

        wcontact.setEditable(false);
        wcontact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wcontact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wcontact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wcontactActionPerformed(evt);
            }
        });
        jPanel5.add(wcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 300, 30));

        wemail.setEditable(false);
        wemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wemailActionPerformed(evt);
            }
        });
        jPanel5.add(wemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 300, 30));

        wname.setEditable(false);
        wname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wnameActionPerformed(evt);
            }
        });
        wname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wnameKeyTyped(evt);
            }
        });
        jPanel5.add(wname, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 300, 30));

        jLabel67.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Search Name :");
        jPanel5.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Flat No :");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, -1, -1));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 590, 20));

        jList4.setBackground(new java.awt.Color(93, 73, 71));
        jList4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jList4.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList4ValueChanged(evt);
            }
        });
        jScrollPane14.setViewportView(jList4);

        jPanel5.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 130, 230));

        jSeparator40.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 60, 250));
        jPanel5.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 150, 10));

        jSeparator41.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 40, 250));
        jPanel5.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 150, 30));

        bnumber.setEditable(false);
        bnumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bnumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnumberActionPerformed(evt);
            }
        });
        jPanel5.add(bnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 90, 30));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, -1, -1));

        fnumber.setEditable(false);
        fnumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fnumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnumberActionPerformed(evt);
            }
        });
        jPanel5.add(fnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 90, 30));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Home Add :");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Block No :");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("E-Mail :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(">>");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, -1));

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 17)); // NOI18N
        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 100, 40));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 640, -1, -1));

        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 140, 30));

        jLabel68.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Member's Name :");
        jPanel5.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jCheckBox2.setText("Outgoing");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jCheckBox3.setText("Incomeing");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image from million-wallpapers.com 1366x768 (3).jpg"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wAddressActionPerformed

    private void wcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wcontactActionPerformed

    private void wemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wemailActionPerformed

    private void wnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wnameActionPerformed

    private static java.sql.Date getCurrentDate() {
    java.util.Date today = new java.util.Date();
    return new java.sql.Date(today.getTime());
}
    private void jList4ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList4ValueChanged
        DBConnection db=new DBConnection();
        try
        {
            db.pstmt=db.con.prepareStatement("select * from member where contact_no=?");
            db.pstmt.setString(1,jList4.getSelectedValue());
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next())
            {
             wname.setText(db.rst.getString(1));
             wAddress.setText(db.rst.getString(2));
             wcontact.setText("+91"+db.rst.getString(4));
             wemail.setText(db.rst.getString(5));
             bnumber.setText(db.rst.getString(9));
             fnumber.setText(db.rst.getString(10));
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jList4ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DBConnection db=new DBConnection();
        try
{
     if(jCheckBox2.isSelected()==true)
     {
    db.pstmt=db.con.prepareStatement("insert into incom_outgoing_details(m_name,home_add,contact_no,email,block_no,flat_no,outgoing_time,curdate) values(?,?,?,?,?,?,curtime(),curdate())");
    db.pstmt.setString(1, wname.getText());
    db.pstmt.setString(2, wAddress.getText());
    db.pstmt.setString(3, wcontact.getText());
    db.pstmt.setString(4, wemail.getText());
    db.pstmt.setString(5, bnumber.getText());
    db.pstmt.setString(6, fnumber.getText());
 
    int i=db.pstmt.executeUpdate();
    if(i>0)
    {
        JOptionPane.showMessageDialog(this,"Detail Submited");
        
    }
    else
    {
        JOptionPane.showMessageDialog(this,"Somthing Went Wrong !");
    }
     }
     else
     {
         if(jCheckBox3.isSelected()==true)
     {
    db.pstmt=db.con.prepareStatement("insert into incom_outgoing_details(m_name,home_add,contact_no,email,block_no,flat_no,incomming_time,curdate) values(?,?,?,?,?,?,curtime(),curdate())");
    db.pstmt.setString(1, wname.getText());
    db.pstmt.setString(2, wAddress.getText());
    db.pstmt.setString(3, wcontact.getText());
    db.pstmt.setString(4, wemail.getText());
    db.pstmt.setString(5, bnumber.getText());
    db.pstmt.setString(6, fnumber.getText());
 
    int i=db.pstmt.executeUpdate();
    if(i>0)
    {
        JOptionPane.showMessageDialog(this,"Detail Submited");
        
    }
    else
    {
        JOptionPane.showMessageDialog(this,"Somthing Went Wrong !");
    }
     }
     }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnumberActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 wname.setText("");
  wAddress.setText("");
   wcontact.setText("");
    wemail.setText("");
    bnumber.setText("");
   fnumber.setText("");
  
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
  jButton1.setBackground(Color.green);
  jButton3.setBackground(Color.red);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
      Color c=new Color(153,153,153);
        jButton3.setBackground(c);   
        jButton1.setBackground(c);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
   Color c=new Color(153,153,153);
        jButton3.setBackground(c);   
        jButton1.setBackground(c);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
 jButton1.setBackground(Color.red);
  jButton3.setBackground(Color.green);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MouseEntered

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
DBConnection db=new DBConnection();
try
{
    DefaultListModel dlm=new DefaultListModel();
    db.pstmt=db.con.prepareStatement("select contact_no from member where m_name like ?");
    db.pstmt.setString(1,"%"+jTextField1.getText()+"%");
    db.rst=db.pstmt.executeQuery();
    while(db.rst.next())
    {
        dlm.addElement(db.rst.getString(1));
    }
    jList4.setModel(dlm);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_jTextField1KeyReleased

    private void bnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnumberActionPerformed

    private void wnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wnameKeyTyped

    }//GEN-LAST:event_wnameKeyTyped

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
if(jCheckBox2.isSelected()==true)     
{
  JOptionPane.showMessageDialog(this,"You Can  Select Only One At A Time !");
jCheckBox3.setSelected(false);
jCheckBox2.setSelected(false);
}

    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
  if(jCheckBox3.isSelected()==true)     
{
  JOptionPane.showMessageDialog(this,"You Can  Select Only One At A Time !");
jCheckBox2.setSelected(false);
jCheckBox3.setSelected(false);
}
      // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncommindOutGoingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncommindOutGoingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncommindOutGoingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncommindOutGoingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncommindOutGoingDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bnumber;
    private javax.swing.JTextField fnumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField wAddress;
    private javax.swing.JTextField wcontact;
    private javax.swing.JTextField wemail;
    private javax.swing.JTextField wname;
    // End of variables declaration//GEN-END:variables
}
