/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SocietyManagmentSystem;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author HarshitMaurya
 */
public class SocietyManagmenetSystem extends javax.swing.JFrame {

    /**
     * Creates new form CouriourManagementSystem
     */
    public SocietyManagmenetSystem() {
        super("Society Managment System");
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jSeparator58 = new javax.swing.JSeparator();
        jSeparator57 = new javax.swing.JSeparator();
        jSeparator56 = new javax.swing.JSeparator();
        jSeparator59 = new javax.swing.JSeparator();
        jButton19 = new javax.swing.JButton();
        jSeparator52 = new javax.swing.JSeparator();
        jSeparator53 = new javax.swing.JSeparator();
        jSeparator54 = new javax.swing.JSeparator();
        jSeparator55 = new javax.swing.JSeparator();
        jButton18 = new javax.swing.JButton();
        jSeparator60 = new javax.swing.JSeparator();
        jSeparator63 = new javax.swing.JSeparator();
        jSeparator62 = new javax.swing.JSeparator();
        jSeparator61 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jSeparator51 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setBackground(new java.awt.Color(0, 51, 51));
        jButton17.setFont(new java.awt.Font("Sitka Heading", 1, 30)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Employee Login");
        jButton17.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton17MouseExited(evt);
            }
        });
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 220, 140));
        jPanel1.add(jSeparator58, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 240, 20));

        jSeparator57.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator57, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 10, 160));
        jPanel1.add(jSeparator56, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 240, 20));

        jSeparator59.setForeground(new java.awt.Color(0, 0, 204));
        jSeparator59.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator59, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 30, 160));

        jButton19.setBackground(new java.awt.Color(0, 51, 51));
        jButton19.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Admin Login");
        jButton19.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton19MouseExited(evt);
            }
        });
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 220, 140));

        jSeparator52.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(jSeparator52, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 240, 20));

        jSeparator53.setForeground(new java.awt.Color(0, 0, 204));
        jSeparator53.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator53, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 30, 160));
        jPanel1.add(jSeparator54, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 240, 20));

        jSeparator55.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator55, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 10, 160));

        jButton18.setBackground(new java.awt.Color(0, 51, 51));
        jButton18.setFont(new java.awt.Font("Sitka Heading", 1, 40)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Exit");
        jButton18.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 0, 0)));
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton18MouseExited(evt);
            }
        });
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 500, 220, 140));
        jPanel1.add(jSeparator60, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, 240, 20));

        jSeparator63.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, 10, 160));
        jPanel1.add(jSeparator62, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 650, 240, 20));

        jSeparator61.setForeground(new java.awt.Color(0, 0, 204));
        jSeparator61.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator61, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 490, 30, 160));

        jLabel40.setFont(new java.awt.Font("Trajan Pro 3", 1, 65)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Society managment system");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));
        jPanel1.add(jSeparator51, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 1090, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image from million-wallpapers.com 1355x723.jpg"))); // NOI18N
        jLabel1.setText("s");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1355, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseEntered
         Color c=new Color(11,22,53);
        jButton17.setBackground(c);
        
        jButton19.setBackground(Color.black);
        jButton18.setBackground(Color.black);
    }//GEN-LAST:event_jButton17MouseEntered

    private void jButton17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseExited
        Color c=new Color(0,51,51);
        jButton17.setBackground(c);
        jButton19.setBackground(c);
        jButton18.setBackground(c);
    }//GEN-LAST:event_jButton17MouseExited

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
new LogINPanelUser().setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseEntered
        jButton17.setBackground(Color.black);
 Color c=new Color(11,22,53);
        jButton19.setBackground(c);
        jButton18.setBackground(Color.black);
    }//GEN-LAST:event_jButton19MouseEntered

    private void jButton19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseExited
        Color c=new Color(0,51,51);
        jButton17.setBackground(c);
        jButton19.setBackground(c);
        jButton18.setBackground(c);
    }//GEN-LAST:event_jButton19MouseExited

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
new LogINPanel().setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseEntered
        jButton19.setBackground(Color.BLACK);
        jButton17.setBackground(Color.BLACK);
     Color c=new Color(11,22,53);
        jButton18.setBackground(c);
    }//GEN-LAST:event_jButton18MouseEntered

    private void jButton18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseExited
        Color c=new Color(0,51,51);
        jButton19.setBackground(c);
        jButton17.setBackground(c);
        jButton18.setBackground(c);
    }//GEN-LAST:event_jButton18MouseExited

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
    int i= JOptionPane.showConfirmDialog(this,"DO You Want To Exit ?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
     if(i == JOptionPane.YES_OPTION)
     {
         System.exit(0);
     }
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CallMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CallMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CallMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CallMaintainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocietyManagmenetSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator52;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator57;
    private javax.swing.JSeparator jSeparator58;
    private javax.swing.JSeparator jSeparator59;
    private javax.swing.JSeparator jSeparator60;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    private javax.swing.JSeparator jSeparator63;
    // End of variables declaration//GEN-END:variables
}
