/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SocietyManagmentSystem;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author HarshitMaurya
 */
public class UpdateEmployeeAndMember extends javax.swing.JFrame {

    /**
     * Creates new form CouriourManagementSystem
     */
    public UpdateEmployeeAndMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel77 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        SengineerID = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel17.setBackground(new java.awt.Color(102, 102, 0));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Trajan Pro 3", 1, 48)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("<<");
        jLabel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel66MouseClicked(evt);
            }
        });
        jPanel17.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel68.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel68.setText("Name :");
        jPanel17.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jLabel69.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jPanel17.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 30, 110, -1));

        jLabel70.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel70.setText("Address :");
        jPanel17.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        jLabel71.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel71.setText("Contact :");
        jPanel17.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        jLabel73.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel73.setText("ID");
        jPanel17.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 140, -1));

        jTextField21.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setToolTipText("");
        jTextField21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 310, 30));

        jTextField22.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setToolTipText("");
        jTextField22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 310, 30));

        jTextField23.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setToolTipText("");
        jTextField23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 310, 30));

        jTextField24.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setToolTipText("");
        jTextField24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 310, 30));

        jTextField25.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.setToolTipText("");
        jTextField25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 310, 30));

        jLabel74.setFont(new java.awt.Font("Trajan Pro 3", 1, 48)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Update details");
        jPanel17.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel76.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel76.setText("E-mail :");
        jPanel17.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, -1));

        jLabel122.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(255, 255, 255));
        jLabel122.setText("<< Control Panel");
        jLabel122.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel122MouseClicked(evt);
            }
        });
        jPanel17.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, -1, -1));

        jButton20.setBackground(new java.awt.Color(204, 204, 204));
        jButton20.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButton20.setText("Search");
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton20MouseExited(evt);
            }
        });
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, -1));

        jButton21.setBackground(new java.awt.Color(204, 204, 204));
        jButton21.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jButton21.setText("Update");
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton21MouseExited(evt);
            }
        });
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, -1, -1));

        jLabel77.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel77.setText("Username :");
        jPanel17.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Employee", "Member" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel17.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel17.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 430, 140));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel17.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 90, 140));
        jPanel17.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 430, 20));
        jPanel17.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 430, 20));

        SengineerID.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        SengineerID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SengineerID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.add(SengineerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 250, 30));

        jLabel75.setBackground(new java.awt.Color(0, 204, 204));
        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image from million-wallpapers.com 1366x768 (7).jpg"))); // NOI18N
        jPanel17.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1340, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1340, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseClicked
this.setVisible(false);
    }//GEN-LAST:event_jLabel66MouseClicked

    private void jLabel122MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel122MouseClicked
this.setVisible(false);


    }//GEN-LAST:event_jLabel122MouseClicked

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        DBConnection db=new DBConnection();
      if(!jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Select"))
       {
        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Employee"))
        {
            if(!SengineerID.equals(""))
            {
            try
            {
             db.pstmt=db.con.prepareStatement("update employee set e_name=?,adress=?,contact_no=?,email=?,username=? where e_id=?");
            db.pstmt.setString(1,jTextField21.getText());
            db.pstmt.setString(2,jTextField22.getText());
            db.pstmt.setString(3,jTextField23.getText());
            db.pstmt.setString(4,jTextField24.getText());
            db.pstmt.setString(5,jTextField25.getText());
          db.pstmt.setString(6,SengineerID.getText());
            int i=db.pstmt.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(this,"Updated Sucessfully");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Data Not Updated");
            }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
            
        }
        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Member"))
        {
             if(!SengineerID.equals(""))
            {
            try
            {
               db.pstmt=db.con.prepareStatement("update member set m_name=?,Adress_inSocity=?,contact_no=?,email=?  where m_id=?");
            db.pstmt.setString(1,jTextField21.getText());
            db.pstmt.setString(2,jTextField22.getText());
            db.pstmt.setString(3,jTextField23.getText());
            db.pstmt.setString(4,jTextField24.getText());
          db.pstmt.setString(5,SengineerID.getText());
            int i=db.pstmt.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(this,"Updated Sucessfully");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Data Not Updated");
            }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        }
        
       }
       else
       {
           JOptionPane.showMessageDialog(this,"Please Select One Opration");
       }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        try
        {
            

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
       DBConnection db=new DBConnection();
       if(!jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Select Type"))
       {
        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Employee"))
        {
            if(!SengineerID.equals(""))
            {
            try
            {
              db.pstmt=db.con.prepareStatement("select * from employee where e_id=?");
              db.pstmt.setString(1,SengineerID.getText());
              db.rst=db.pstmt.executeQuery();
              if(db.rst.next())
              {
                jTextField21.setText(db.rst.getString(1));
                jTextField22.setText(db.rst.getString(2));
                jTextField23.setText(db.rst.getString(4));
                jTextField24.setText(db.rst.getString(5));
                jTextField25.setText(db.rst.getString(9));
              }
              else
              {
                  JOptionPane.showMessageDialog(this,"Record Not found");
              }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
            
        }
        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Member"))
        {
             if(!SengineerID.equals(""))
            {
            try
            {
              db.pstmt=db.con.prepareStatement("select * from member where m_id=?");
              db.pstmt.setString(1,SengineerID.getText());
              db.rst=db.pstmt.executeQuery();
              if(db.rst.next())
              {
                jTextField21.setText(db.rst.getString(1));
                jTextField22.setText(db.rst.getString(2));
                jTextField23.setText(db.rst.getString(4));
                jTextField24.setText(db.rst.getString(6));
                jLabel77.setVisible(false);
                jTextField25.setVisible(false);
              }
              else
              {
                  JOptionPane.showMessageDialog(this,"Record Not found");
              }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        }
        
       }
       else
       {
           JOptionPane.showMessageDialog(this,"Please Select One Opration");
       }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Employee"))
{
 jLabel73.setText("Employee ID :");
}
if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Member"))
{
    jLabel73.setText("Member ID :");
}
    jLabel77.setVisible(true);
                jTextField25.setVisible(true);      
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseExited
        Color c=new Color(204,204,204);
        jButton20.setBackground(c);   
        jButton21.setBackground(c);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton20MouseExited

    private void jButton21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseExited
 Color c=new Color(204,204,204);
        jButton20.setBackground(c);   
        jButton21.setBackground(c);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21MouseExited

    private void jButton20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseEntered
jButton20.setBackground(Color.GREEN);   
        jButton21.setBackground(Color.RED);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton20MouseEntered

    private void jButton21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseEntered
jButton20.setBackground(Color.GREEN);   
        jButton21.setBackground(Color.RED);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton21MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployeeAndMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployeeAndMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployeeAndMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployeeAndMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEmployeeAndMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SengineerID;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    // End of variables declaration//GEN-END:variables
}
