/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

import javax.swing.JOptionPane;

/**
 *
 * @author HarshitMaurya
 */
public class AdminResult extends javax.swing.JFrame {

    /**
     * Creates new form AdminResult
     */
    public AdminResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tmother = new javax.swing.JTextField();
        tfather = new javax.swing.JTextField();
        troll = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tcontact = new javax.swing.JTextField();
        tmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tc = new javax.swing.JTextField();
        tdata = new javax.swing.JTextField();
        tgraphics = new javax.swing.JTextField();
        tjava = new javax.swing.JTextField();
        torg = new javax.swing.JTextField();
        tnetworking = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        p = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Maharishi University Lucknow");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 0, 410, 67));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student's Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 31, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Father Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 31, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mother Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 85, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Roll Number");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 85, -1, -1));

        tname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 27, 254, 29));

        tmother.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tmother.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tmother.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tmother, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 81, 254, 29));

        tfather.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfather.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfather.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tfather, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 27, 254, 29));

        troll.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        troll.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        troll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(troll, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 81, 254, 29));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-mail");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 138, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 149, -1, -1));

        tcontact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tcontact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tcontact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 137, 254, 29));

        tmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 134, 254, 29));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Java Programming");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Computer Networking");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Computer Graphics");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Computer Organization");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 289, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Data Structure");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, -1, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("C Programming");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 351, -1, -1));

        tc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 350, 240, 29));

        tdata.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tdata.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 410, 240, 29));

        tgraphics.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tgraphics.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tgraphics.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tgraphics, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 231, 29));

        tjava.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tjava.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tjava.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tjava, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 231, 29));

        torg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        torg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        torg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(torg, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 240, 29));

        tnetworking.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tnetworking.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tnetworking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tnetworking, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 231, 29));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 160, 40));
        jPanel2.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 650, 180, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Picture1.png"))); // NOI18N
        jLabel16.setText("jLabel15");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 680));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 1170, -1));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 160, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Picture1.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try
      {
        LoginPage lg=new  LoginPage();
        String name=tname.getText();
        String roll=troll.getText();
        String mail=tmail.getText();
        String father=tfather.getText();
        String mother=tmother.getText();
        String contact=tcontact.getText();
        String  java =tjava.getText();
        String networking =tnetworking.getText();
        String  graphics=tgraphics.getText();
        String  org =torg.getText();
        String  c =tc.getText();
        String   data =tdata.getText();
         lg.pstmt=lg.con.prepareStatement("insert into log_info(Sname,Sroll,Semail,Sfather,Smother,Scontact,Sjava,Snetworking,Scg,Sco,Sc,Sdata) values(?,?,?,?,?,?,?,?,?,?,?,?)");
        lg.pstmt.setString(1, name);
          lg.pstmt.setString(2,roll );
          lg.pstmt.setString(3,mail );
          lg.pstmt.setString(4,father );
          lg.pstmt.setString(5,mother );
          lg.pstmt.setString(6,contact );
          lg.pstmt.setString(7,java );
          lg.pstmt.setString(8,networking );
          lg.pstmt.setString(9,graphics );
          lg.pstmt.setString(10,org );
          lg.pstmt.setString(11,c );
          lg.pstmt.setString(12,data );
          int i=lg.pstmt.executeUpdate();
          if(i>0)
          {
              JOptionPane.showMessageDialog(this, "Succesfully Submited");
          }
          
      }
      catch(Exception e)
      {
       e.printStackTrace();
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField p;
    private javax.swing.JTextField tc;
    private javax.swing.JTextField tcontact;
    private javax.swing.JTextField tdata;
    private javax.swing.JTextField tfather;
    private javax.swing.JTextField tgraphics;
    private javax.swing.JTextField tjava;
    private javax.swing.JTextField tmail;
    private javax.swing.JTextField tmother;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tnetworking;
    private javax.swing.JTextField torg;
    private javax.swing.JTextField troll;
    // End of variables declaration//GEN-END:variables
}
