/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

/**
 *
 * @author HarshitMaurya
 */
public class Marksheet extends javax.swing.JFrame {

    /**
     * Creates new form Marksheet
     */
    public Marksheet() {
        super("Maharishi University Of Information Technology");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        father = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        name5 = new javax.swing.JLabel();
        roll = new javax.swing.JLabel();
        name7 = new javax.swing.JLabel();
        name8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        sj = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        sn = new javax.swing.JLabel();
        sg = new javax.swing.JLabel();
        so = new javax.swing.JLabel();
        scp = new javax.swing.JLabel();
        sdata = new javax.swing.JLabel();
        prcn = new javax.swing.JLabel();
        prcg = new javax.swing.JLabel();
        prco = new javax.swing.JLabel();
        prdata = new javax.swing.JLabel();
        javap = new javax.swing.JLabel();
        networking = new javax.swing.JLabel();
        graphics = new javax.swing.JLabel();
        corg = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        tjava = new javax.swing.JLabel();
        tn = new javax.swing.JLabel();
        tg = new javax.swing.JLabel();
        tco = new javax.swing.JLabel();
        tc = new javax.swing.JLabel();
        tdata = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        tsess = new javax.swing.JLabel();
        tpr = new javax.swing.JLabel();
        tth = new javax.swing.JLabel();
        totle = new javax.swing.JLabel();

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("CAMPUS");

        name4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name4.setText("HARSHIT MAURYA");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/muit-logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 1, 92, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(123, 8, 17));
        jLabel2.setText("MAHARISHI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(123, 8, 17));
        jLabel3.setText("UNIVERSITY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 56, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Sl.No.005299");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 12, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setText("STATEMENT OF MARKS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Diploma in Engineering");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("NAME");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 187, 43, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("FATHER'S NAME");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("COURSE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 233, 61, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("CAMPUS");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 268, 61, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("ENROLLMENT NO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 187, 125, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("ROLL NO");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("SESSION");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 268, 69, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("SEMESTER");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 233, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText(":");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 187, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText(":");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 210, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText(":");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 233, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText(":");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 268, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText(":");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 187, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText(":");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 210, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText(":");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 233, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText(":");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 268, -1, -1));

        name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name.setText("HARSHIT MAURYA");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 189, 142, -1));

        name1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name1.setText("DIPLOMA ( COMPUTER SCIENCE )");
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 235, 213, -1));

        father.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        father.setText("RAM NARESH MAURYA");
        jPanel1.add(father, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 212, 142, -1));

        name3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name3.setText("MAIN CAMPUS");
        jPanel1.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 270, 142, -1));

        name5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name5.setText("MUIT0117011029");
        jPanel1.add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 189, 142, -1));

        roll.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        roll.setText("1701011102005");
        jPanel1.add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 212, 142, -1));

        name7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name7.setText("I");
        jPanel1.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 235, 142, -1));

        name8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name8.setText("2018-19");
        jPanel1.add(name8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 142, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 760, 160, 120));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 870, 230));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 370, 30));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, 290));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 200, 290));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 120, 260));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 40, 260));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 40, 260));

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 110, 260));

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 40, 260));

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 870, 330));

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, 870, 120));

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 800, 870, 40));

        jSeparator17.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 760, 50, 120));

        jSeparator18.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 760, 50, 120));

        jSeparator19.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 760, 50, 120));

        jSeparator20.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 760, 310, 120));

        jSeparator21.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 760, 50, 120));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Paper code");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 70, -1));

        jSeparator22.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 870, 170));

        jSeparator23.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 870, 90));

        jSeparator24.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 870, 30));

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel26.setText("Java Programming");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 130, -1));

        jLabel27.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel27.setText("Computer Networking");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 150, -1));

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel28.setText("Computer Graphics");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 130, -1));

        jLabel29.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel29.setText("Computer Organizetion");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 160, -1));

        jLabel30.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel30.setText("C Programming");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 130, -1));

        jLabel31.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel31.setText("Data Structure");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 130, -1));

        jLabel33.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel33.setText("Name of Paper");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 130, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("DAH101");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("DAS101");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setText("DCS101");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("DAS102");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("DAS103");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setText("DME151");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setText("Maximum Marks");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setText("Marks Obtained");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, -1));

        jLabel40.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel40.setText("Totle Aggregate Marks");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 578, -1, 30));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setText("Result :           Pass");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 620, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setText("Date:             05/10/2018");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setText("Sess.");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setText("Pr.");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 20, 20));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setText("Th.");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 20, 20));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setText("Total");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 40, 20));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel47.setText("Sess.");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 50, 20));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel48.setText("Pr.");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 50, 20));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setText("Th.");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 50, 20));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setText("Total");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 40, 20));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel51.setText("30");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel52.setText("30");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel53.setText("30");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel54.setText("30");
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel55.setText("30");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, -1, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel56.setText("30");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, -1));

        sj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sj.setText("30");
        jPanel1.add(sj, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, -1, -1));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel63.setText("50");
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel64.setText("50");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, -1, -1));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel65.setText("50");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, -1, -1));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel66.setText("50");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, -1, -1));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel67.setText("70");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, -1, -1));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel68.setText("70");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel69.setText("70");
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, -1, -1));

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel70.setText("70");
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, -1, -1));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel71.setText("70");
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, -1, -1));

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel72.setText("100");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel73.setText("150");
        jPanel1.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, -1));

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel74.setText("80");
        jPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, -1, -1));

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel75.setText("100");
        jPanel1.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, -1, -1));

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel76.setText("150");
        jPanel1.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel77.setText("150");
        jPanel1.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, -1, -1));

        sn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sn.setText("28");
        jPanel1.add(sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 414, 20, 30));

        sg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sg.setText("27");
        jPanel1.add(sg, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));

        so.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        so.setText("29");
        jPanel1.add(so, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, -1, -1));

        scp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        scp.setText("24");
        jPanel1.add(scp, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, -1, -1));

        sdata.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sdata.setText("27");
        jPanel1.add(sdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, -1, -1));

        prcn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        prcn.setText("47");
        jPanel1.add(prcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, -1, -1));

        prcg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        prcg.setText("48");
        jPanel1.add(prcg, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, -1));

        prco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        prco.setText("46");
        jPanel1.add(prco, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, -1, -1));

        prdata.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        prdata.setText("49");
        jPanel1.add(prdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, -1, -1));

        javap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        javap.setText("65");
        jPanel1.add(javap, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, -1, -1));

        networking.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        networking.setText("64");
        jPanel1.add(networking, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, -1, -1));

        graphics.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        graphics.setText("66");
        jPanel1.add(graphics, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, -1, -1));

        corg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        corg.setText("68");
        jPanel1.add(corg, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, -1, -1));

        c.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        c.setText("61");
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, -1, -1));

        data.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        data.setText("60");
        jPanel1.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, -1, -1));

        tjava.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tjava.setText("102");
        tjava.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(tjava, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 390, 30, -1));

        tn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tn.setText("129");
        jPanel1.add(tn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, -1, -1));

        tg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tg.setText("131");
        jPanel1.add(tg, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, -1, -1));

        tco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tco.setText("143");
        jPanel1.add(tco, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, -1, -1));

        tc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tc.setText("102");
        jPanel1.add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 520, 30, -1));

        tdata.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tdata.setText("136");
        jPanel1.add(tdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, -1, -1));

        jLabel99.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel99.setText("180");
        jPanel1.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, -1, -1));

        jLabel100.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel100.setText("200");
        jPanel1.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, -1, -1));

        jLabel101.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel101.setText("350");
        jPanel1.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, -1, -1));

        jLabel102.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel102.setText("730");
        jPanel1.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 590, -1, -1));

        tsess.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tsess.setText("165");
        jPanel1.add(tsess, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 590, 30, -1));

        tpr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tpr.setText("190");
        jPanel1.add(tpr, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 590, -1, -1));

        tth.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tth.setText("384");
        jPanel1.add(tth, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, -1, -1));

        totle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totle.setText("719");
        jPanel1.add(totle, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 590, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
          //  jLabel26.util.logging.Logger.getLogger(Marksheet.class.getName()).log(jLabel26.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
          //  jLabel26.util.logging.Logger.getLogger(Marksheet.class.getName()).log(jLabel26.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
           // jLabel26.util.logging.Logger.getLogger(Marksheet.class.getName()).log(jLabel26.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //jLabel26.util.logging.Logger.getLogger(Marksheet.class.getName()).log(jLabel26.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   java.awt.EventQueue.invokeLater(new Runnable()  {
            public void run() {
                new Marksheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel c;
    public javax.swing.JLabel corg;
    public javax.swing.JLabel data;
    public javax.swing.JLabel father;
    public javax.swing.JLabel graphics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel javap;
    public javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel name8;
    public javax.swing.JLabel networking;
    public javax.swing.JLabel prcg;
    public javax.swing.JLabel prcn;
    public javax.swing.JLabel prco;
    public javax.swing.JLabel prdata;
    public javax.swing.JLabel roll;
    public javax.swing.JLabel scp;
    public javax.swing.JLabel sdata;
    public javax.swing.JLabel sg;
    public javax.swing.JLabel sj;
    public javax.swing.JLabel sn;
    public javax.swing.JLabel so;
    public javax.swing.JLabel tc;
    public javax.swing.JLabel tco;
    public javax.swing.JLabel tdata;
    public javax.swing.JLabel tg;
    public javax.swing.JLabel tjava;
    public javax.swing.JLabel tn;
    public javax.swing.JLabel totle;
    public javax.swing.JLabel tpr;
    public javax.swing.JLabel tsess;
    public javax.swing.JLabel tth;
    // End of variables declaration//GEN-END:variables


}
